version: "3.7"
services:
  # application
  app:
    build:
      context: .
      dockerfile: "./laravel/Dockerfile"
    working_dir: /var/www
    volumes:
      - ./www:/var/www
  # web server
  web:
    build:
      context: .
      dockerfile: "./nginx/Dockerfile"
    working_dir: /var/www
    volumes:
      - ./www:/var/www
    depends_on:
      - "app"
    ports:
      - 8080:80

  postgres:
    build:
      context: .
      dockerfile: "./postgres/Dockerfile"
      args:
        db_name: "metabase"
        db_user: "postgres"
        db_password: postgres"
        db_port: 5432
    restart: always
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=metabase
    ports:
      - "5433:5432"

  metabase:
    image: metabase/metabase
    restart: always
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
      MB_DB_TYPE: "postgres"
      MB_DB_DBNAME: "metabase"
      MB_DB_PORT: "5432"
      MB_DB_USER: "postgres"
      MB_DB_HOST: "postgres"
      MB_DB_PASS: "postgres"
      JAVA_TIMEZONE: "Asia/Jakarta"
    ports:
      - "3000:3000"
    volumes:
      - "metabase-data:/metabase-data"
    depends_on:
      - "postgres"

volumes:
  postgres-data:
  metabase-data:
